// frontend/src/views/Catalog.vue
<template>
  <div class="w-full min-h-[956px] bg-[#f2f2f2] pt-10 px-10">
    <div class="w-full max-w-[1360px] mx-auto rounded-[20px] shadow-[0px_4px_20px_#00000040] bg-white p-8">
      <h1 class="font-['Open_Sans',Helvetica] font-bold text-[#263238] text-[55px] tracking-[-0.82px] leading-tight mb-6">
        Catálogo de produtos
      </h1>
      <p class="font-['Open_Sans',Helvetica] font-normal text-[#9e9d9d] text-2xl tracking-[-0.36px]">
        Encontre os melhores produtos do mercado
      </p>
    </div>
  </div>
</template>

// frontend/src/screens/Catalog/Catalog.tsx
import React from "react";
import { Card } from "../../components/ui/card";

export const Catalog = (): JSX.Element => {
  return (
    <div className="w-full min-h-[956px] bg-[#f2f2f2] pt-10 px-10">
      <Card className="w-full max-w-[1360px] mx-auto rounded-[20px] shadow-[0px_4px_20px_#00000040] p-8">
        <h1 className="font-['Open_Sans',Helvetica] font-bold text-[#263238] text-[55px] tracking-[-0.82px] leading-tight mb-6">
          Catálogo de produtos
        </h1>
        <p className="font-['Open_Sans',Helvetica] font-normal text-[#9e9d9d] text-2xl tracking-[-0.36px]">
          Encontre os melhores produtos do mercado
        </p>
      </Card>
    </div>
  );
};
