// frontend/src/App.tsx
import React from "react";
import { BrowserRouter, Routes, Route } from "react-router-dom";
import { Navbar } from "./components/Navbar";
import { Home } from "./screens/Home";
import { Catalog } from "./screens/Catalog";
import { Admin } from "./screens/Admin";

export default function App() {
  return (
    <BrowserRouter>
      <div className="bg-white flex flex-row justify-center w-full">
        <div className="bg-white overflow-hidden w-full max-w-[1440px]">
          <div className="relative min-h-screen">
            <Navbar />
            <Routes>
              <Route path="/" element={<Home />} />
              <Route path="/catalog" element={<Catalog />} />
              <Route path="/admin" element={<Admin />} />
            </Routes>
          </div>
        </div>
      </div>
    </BrowserRouter>
  );
}

// frontend/src/App.vue
<template>
  <div class="bg-white flex flex-row justify-center w-full">
    <div class="bg-white overflow-hidden w-full max-w-[1440px]">
      <div class="relative min-h-screen">
        <Navbar />
        <router-view></router-view>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import Navbar from './components/Navbar.vue';
</script>
